# DB connection settings
# conninfo to be supplied via the "-conninfo" command-line parameter.
connopen = 2
connidle = 2
connlife = "10m"

# Workload settings
interval = "0s"
batch = 5000
concurrent = 100

# Other default settings
httptimeout = "30s"
